# Generated by Django 4.1.7 on 2023-09-11 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last',
            new_name='last_name',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
